### ISSUE TITLE
Amcrest Doorbell

### ISSUE THREAD

**Issue by chadlyy** [tchellomello/python-amcrest#151]
Amcrest Doorbell works great with this by the way.  Can you add a doorbell sensor too?

**Comment by MYeager1967** [comment]
Exactly how are you using this with the doorbell? Can you set something up to monitor for motion start/stop events? I'm trying to figure out how to do it...

**Comment by blademckain** [comment]
i think, the Doorbell create a specific event  ( CallNoAnswered / IgnoreInvite ) when someone push the button
best is to have a binary sensor ( ON/OFF ) that trigger when someone push the button

**Comment by FrnchFrgg** [comment]
Indeed, and I use these events for automation in HA.

**Comment by pixeldoc2000** [comment]
See #137 and #162

**Comment by PanicRide** [comment]
FYI... now that the doorbell button press events work, I tried to add it to Home Assistant's integration, but it got rejected because it would require a change to the YAML config schema.  The integration needs to be overhauled to support the new UI config flows before such features can be added. :(

https://github.com/home-assistant/core/pull/66302

However, you can still manually subscribe to the event with an automation trigger, or by setting up your own template binary sensor to listen for this event:

```
platform: event
event_type: amcrest
event_data:
  camera: <AMCREST DEVICE FRIENDLY NAME>
  event: CallNoAnswered
  payload:
    action: Start
```
