### ISSUE TITLE
Is it possible to choose NVR channel 

### ISSUE THREAD

**Issue by gihad** [tchellomello/python-amcrest#89]
I'm using this library through the latest Home Assistant, I successfully added my Amcrest NVR with this:

```
# Amcrest NVR
amcrest:
  - host: NVR_IP
    username: <login>
    password: <password>
    sensors:
      - motion_detector
      - sdcard
      - ptz_preset
```

My Overview page in HA started showing images from the First channel in the NVR.
Is it currently possible to specify the channel? So I can get other channels? Are there other implications of doing this?

In general I'm trying to avoid connecting directly to the Camera's IP, I'm thinking it's more efficient to connect to the NVR.

**Comment by dougsland** [comment]
@gihad most of our API calls have channels params. Not sure how we will integrate with HA. Marcelo, probably is aware of it. @tchellomello

**Comment by tchellomello** [comment]
Not sure about that too @gihad and @dougsland. 

@gihad do you know if the NVR has a bindable API?

**Comment by thefarelkid** [comment]
Hi @Klathmon. I too have an Amcrest NVR.  I was able to log in directly to the port 10080 through the NVR, but only if I'm logged into the NVR.  Otherwise, the page can't be reached.  I think that's the reason why when I load my config in Home Assistant, I get the error below.  Any help would be appreciated.

Unable to connect to Amcrest camera: HTTPConnectionPool(host='192.168.29.209', port=10080): Max retries exceeded with url: /cgi-bin/magicBox.cgi?action=getMachineName (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73e36f10>: Failed to establish a new connection: [Errno 111] Connection refused',))

My configuration.yaml
```
camera:
  - platform: amcrest
amcrest:
  - host: 192.168.29.209
    port: 10080
    username: admin
    password: admin #I also tried my normal password and it didn't work either.
    name: NVR

```

**Comment by Klathmon** [comment]
@thefarelkid Well another workaround is to not run the cameras "through" your NVR, but to instead run them through your normal router, but the "add" them to the NVR manually through it's UI.

This is what I ended up doing, so each of my cameras has an IP on my "normal" network, and then the NVR logs into them through the normal network and saves all their recordings, and I have full access to all of them from my "normal" network.

The only downside is that if you are using PoE, then you need to power them with another PoE adapter.

**Comment by mohesles** [comment]
Wouldn't it be just a matter of exposing the channel as a config parameter in home-assistant?
for example... I can see the different streams by using the urls as in:
http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=0&subtype=1
http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=1&subtype=1
http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=2&subtype=1
http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=3&subtype=1

setting them as individual IP cameras is kinda weird and sometimes some work and others dont, plus I have no advanced controls

**Comment by mohesles** [comment]
> @mohesles can you be more specific about what you mean by "exposing the channel as a config parameter? 

In the rest api for snapshots, you can use the channel attribute to see different feeds in an NVR. 
http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=0&subtype=1 would get a snapshot of the 1st camera in the NVR while http://user:pass@NVRs_IP/cgi-bin/snapshot.cgi?channel=1&subtype=1
would show the second camera, and so on.

So I was wondering if there might be a way to let this attribute to be specified. Or something like that?

amcrest:
  - host: IP_ADDRESS_NVR
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    **channel: 0**

 - host: IP_ADDRESS_NVR
   username: YOUR_USERNAME
   password: YOUR_PASSWORD
   **channel: 1**
   resolution: low  _[based on the subtype?]_

**Comment by BenNeumeister** [comment]
Not sure it's that simple.
Btw, I'm in the same boat. 

From snahshot.py
```
channel:
                Values according with Amcrest API:
                0 - regular snapshot
                1 - motion detection snapshot
                2 - alarm snapshot
```

**Comment by thefarelkid** [comment]
I'm still hoping to get this working. Has anyone played around with it? We definitely can get snapshots of each channel, but I don't know if that translates to full functionality of the cameras can be utilized by home assistant. ie: motion sensor triggering an automation.

**Comment by theclevercrib** [comment]
I noticed this hasn't been updated recently, but I also would like to use various channels of the NVR ... and in addition, I would like to be able to activate/deactivate motion recording per channel so I can use the switch in conjunction with automatons in Home Assistant.

**Comment by mohesles** [comment]
Any updates anyone?

**Comment by thefarelkid** [comment]
This did work for me pretty well until I realized that the Pi I was running my home assistant on was idling around 80% load.  Note that this isn't the Amcrest component, so nothing specific to that component works, but I was able to get each camera connected to the NVR to come through by making each channel specific to that camera.  

```
camera:
  - platform: ffmpeg
    name: Camera 1
    input: -rtsp_transport tcp -i rtsp://admin:[passowd]@[nvrIPaddress]:554/cam/realmonitor?channel=1&subtype=1
  - platform: ffmpeg
    name: Camera 2
    input: -rtsp_transport tcp -i rtsp://admin:[passowd]@[nvrIPaddress]:554/cam/realmonitor?channel=2&subtype=1
  - platform: ffmpeg
    name: Camera 3
    input: -rtsp_transport tcp -i rtsp://admin:[passowd]@[nvrIPaddress]:554/cam/realmonitor?channel=3&subtype=1`
```
